### ISSUE TITLE
Extension is grey'd out - Chrome

### ISSUE THREAD

**Issue by rwinn1103** [qualweb/qualweb-extension#16]
I've been attempting to use Qualweb via the browser extension on Chrome version 113.0.5672.92. However, the extension continually appears to be grey'd out. I have tried to set up the extension through Chrome and from cloning this repository: neither worked. Furthermore, I updated my Chrome to the latest version, and I am still running into the same error. Any potential solutions?

**Comment by carlosapaduarte** [comment]
@rwinn1103 The extension creates a new tab on the Dev Tools window. That is where you interact with the extension. Can you check if the tab does not appear for you?

**Comment by rwinn1103** [comment]
Ahh I initially misunderstood how to to interact with the extension properly. With your comment in mind, I was able find the new tab and use Qualweb successfully. Thank you for the information!
