### ISSUE TITLE
Extension broken after dependency update?

### ISSUE THREAD

**Issue by Tellus** [qualweb/qualweb-extension#18]
Hey hey,

Did the recent update break something? Installing the extension fresh on Chrome, and running it (used https://www.inqludeit.dk as my example) leaves the extension hanging on "Ending evaluation".

Console has this output:

```
TypeError: Cannot read properties of undefined (reading 'translate')
    at new t (wcag.js:1:6738)
    at new WCAGTechniques (wcag.js:1:1075)
    at 160 (wcag.js:1:3848)
    at n (wcag.js:1:85794)
    at wcag.js:1:85834
    at wcag.js:1:85935
```

I'm guessing that it might be missing updates to @qualweb/locale after some ACT rules were repurposed as techniques and best practices?

**Comment by carlosapaduarte** [comment]
New version has been submitted for publishing. It has a fix in one ACT rule (R67) that was breaking on your website (the online evaluator was also breaking). 
When it gets approved can you check if the issue if fixed on your side? The new version runs fine locally.

**Comment by Tellus** [comment]
I think the new version got out sometime yesterday.

Seems like it works now (at least on the pages I've tried).

It still outputs the error in the debug console, though. Might be affecting other translations, but for us this is fine :+1:

**Comment by carlosapaduarte** [comment]
I'll need to look into that later, but it seems we can close this one, correct?
